
server:
  port: 9009
spring:
  application:
    name: eureka-consumer-ribbon-hystrix

eureka:
  client:
      service-url:
            defaultZone: http://localhost:9001/eureka/
      #register-with-eureka: false

