
spring:
  application:
    name: eureka-client-prvider
server:
  port: 9006
eureka:
  client:
      service-url:
            defaultZone: http://localhost:9001/eureka/
  instance:
      instance-id: eureka-client-prvider02
      prefer-ip-address: true

provider:
  name: provider2
