
spring:
  application:
    name: eureka-client-prvider


server:
  port: 9003
eureka:
  client:
      service-url:
            defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: eureka-client-prvider01
    prefer-ip-address: true

provider:
  name: provider1
