
server:
  port: 9092
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    service-url:
       defaultZone: http://localhost:9001/eureka/
  instance:
    instance-id: eureka-zuul
    prefer-ip-address: true
zuul:
  routes:
    eureka-client-prvider:
      path: /provider/**
      serviceId: eureka-client-prvider


