
server:
  port: 9007
spring:
  application:
    name: eureka-client-consumer-ribbo-feign
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:9001/eureka/
    register-with-eureka: false

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: true




