
server:
  port: 9091
spring:
  application:
    name: eureka-consumer-feign-hystrix
eureka:
  instance:
    instance-id: consumer-feign-hystrix01
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
    #register-with-eureka: false

feign:
  hystrix:
    enabled: true